/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page. Use "home" for the homepage (served at /). All other slugs are served at /slug.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Upload an MP4 video file for the hero background.
             */
            video: string | Media;
            /**
             * Still image shown until the video can play. Export a JPEG/WebP frame from your video for best results.
             */
            posterImage?: (string | null) | Media;
            /**
             * Solid color behind the video while it loads (e.g. #1a237e).
             */
            fallbackBackgroundColor?: string | null;
            primaryButtonText?: string | null;
            primaryButtonUrl?: string | null;
            secondaryButtonText?: string | null;
            secondaryButtonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            exploreButtonText?: string | null;
            offerings?:
              | {
                  title: string;
                  description: string;
                  image?: (string | null) | Media;
                  servicesList?:
                    | {
                        item: string;
                        id?: string | null;
                      }[]
                    | null;
                  imagePosition?: ('top' | 'bottom') | null;
                  backgroundImage?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'core-offerings';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            exploreButtonText?: string | null;
            projects?:
              | {
                  title?: string | null;
                  category?: string | null;
                  /**
                   * Use a single route like /event or /brand-launch for the project detail page.
                   */
                  route?: string | null;
                  image?: (string | null) | Media;
                  video?: (string | null) | Media;
                  size?: ('large' | 'small') | null;
                  projectDescription?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            ctaButtonText?: string | null;
            clients?:
              | {
                  name: string;
                  logo?: (string | null) | Media;
                  row?: ('1' | '2' | '3' | '4') | null;
                  order?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-clients';
          }
        | {
            sections?:
              | {
                  sectionLabel?: string | null;
                  mainHeading?: string | null;
                  description?: string | null;
                  featuresTitle?: string | null;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  approachSteps?:
                    | {
                        title: string;
                        description: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-brands-choose';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            description?: string | null;
            studioImages?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            perfectFor?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            detailsSection?: {
              title?: string | null;
              description?: string | null;
              locationTitle?: string | null;
              locationAddress?: string | null;
              bookButtonText?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'studio-section';
          }
        | {
            mainTitle?: string | null;
            description?: string | null;
            backgroundImage?: (string | null) | Media;
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero';
          }
        | {
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  servicesTitle?: string | null;
                  services?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  idealForLabel?: string | null;
                  idealForTags?:
                    | {
                        tag: string;
                        id?: string | null;
                      }[]
                    | null;
                  backgroundImage?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'service-cards';
          }
        | {
            mainTitle?: string | null;
            industries?:
              | {
                  name: string;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industries';
          }
        | {
            title?: string | null;
            description?: string | null;
            backgroundImage?: (string | null) | Media;
            bulletPoints?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight-card';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: string | Page;
    } | null;
    url?: string | null;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              video?: T;
              posterImage?: T;
              fallbackBackgroundColor?: T;
              primaryButtonText?: T;
              primaryButtonUrl?: T;
              secondaryButtonText?: T;
              secondaryButtonUrl?: T;
              id?: T;
              blockName?: T;
            };
        'core-offerings'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              exploreButtonText?: T;
              offerings?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    servicesList?:
                      | T
                      | {
                          item?: T;
                          id?: T;
                        };
                    imagePosition?: T;
                    backgroundImage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              exploreButtonText?: T;
              projects?:
                | T
                | {
                    title?: T;
                    category?: T;
                    route?: T;
                    image?: T;
                    video?: T;
                    size?: T;
                    projectDescription?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-clients'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              ctaButtonText?: T;
              clients?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    row?: T;
                    order?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-brands-choose'?:
          | T
          | {
              sections?:
                | T
                | {
                    sectionLabel?: T;
                    mainHeading?: T;
                    description?: T;
                    featuresTitle?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    approachSteps?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'studio-section'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              studioImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              perfectFor?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              detailsSection?:
                | T
                | {
                    title?: T;
                    description?: T;
                    locationTitle?: T;
                    locationAddress?: T;
                    bookButtonText?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'page-hero'?:
          | T
          | {
              mainTitle?: T;
              description?: T;
              backgroundImage?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'service-cards'?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    servicesTitle?: T;
                    services?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    idealForLabel?: T;
                    idealForTags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    backgroundImage?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industries?:
          | T
          | {
              mainTitle?: T;
              industries?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'highlight-card'?:
          | T
          | {
              title?: T;
              description?: T;
              backgroundImage?: T;
              bulletPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  navigation?:
    | {
        label: string;
        /**
         * Use /services to link to the Services page route. Use #section-id for home-page scroll anchors (e.g. #about, #studio, #work, #contact).
         */
        url: string;
        hasDropdown?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    text: string;
    url: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  contactSection: {
    title: string;
    subtitle: string;
    formTitle: string;
  };
  /**
   * Select the Payload form definition used to store Start The Conversation submissions.
   */
  contactForm?: (string | null) | Form;
  companyInfo: {
    brandName: string;
    advertising: string;
    tagline: string;
    phone: string;
    email: string;
    location: string;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'instagram' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteTitle: string;
  siteDescription: string;
  ogImage?: (string | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        hasDropdown?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        formTitle?: T;
      };
  contactForm?: T;
  companyInfo?:
    | T
    | {
        brandName?: T;
        advertising?: T;
        tagline?: T;
        phone?: T;
        email?: T;
        location?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}