/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page. Use "home" for the homepage (served at /). All other slugs are served at /slug.
   */
  slug: string;
  layout?:
    | (
        | {
            /**
             * Upload an MP4 video file for the hero background.
             */
            video: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            exploreButtonText?: string | null;
            offerings?:
              | {
                  title: string;
                  description: string;
                  color?: ('dark-blue' | 'dark-gray' | 'teal' | 'purple') | null;
                  image?: (string | null) | Media;
                  imagePosition?: ('top' | 'bottom') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'core-offerings';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            exploreButtonText?: string | null;
            projects?:
              | {
                  title: string;
                  description?: string | null;
                  category?: string | null;
                  image?: (string | null) | Media;
                  size?: ('large' | 'small') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projects';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            ctaButtonText?: string | null;
            clients?:
              | {
                  name: string;
                  logo?: (string | null) | Media;
                  row?: ('1' | '2' | '3' | '4') | null;
                  order?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featured-clients';
          }
        | {
            sections?:
              | {
                  sectionLabel?: string | null;
                  mainHeading?: string | null;
                  description?: string | null;
                  featuresTitle?: string | null;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  approachSteps?:
                    | {
                        title: string;
                        description: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'why-brands-choose';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            description?: string | null;
            studioImages?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            perfectFor?:
              | {
                  item: string;
                  id?: string | null;
                }[]
              | null;
            detailsSection?: {
              title?: string | null;
              description?: string | null;
              locationTitle?: string | null;
              locationAddress?: string | null;
              bookButtonText?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'studio-section';
          }
        | {
            mainTitle?: string | null;
            description?: string | null;
            images?:
              | {
                  image: string | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'page-hero';
          }
        | {
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  color?: ('dark-blue' | 'dark-gray' | 'teal' | 'purple') | null;
                  servicesTitle?: string | null;
                  services?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  idealForLabel?: string | null;
                  idealForTags?:
                    | {
                        tag: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'service-cards';
          }
        | {
            mainTitle?: string | null;
            industries?:
              | {
                  name: string;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'industries';
          }
        | {
            title?: string | null;
            description?: string | null;
            bulletPoints?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlight-card';
          }
        | {
            sectionLabel?: string | null;
            mainTitle?: string | null;
            description?: string | null;
            buttonText?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta-section';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              video?: T;
              id?: T;
              blockName?: T;
            };
        'core-offerings'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              exploreButtonText?: T;
              offerings?:
                | T
                | {
                    title?: T;
                    description?: T;
                    color?: T;
                    image?: T;
                    imagePosition?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projects?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              exploreButtonText?: T;
              projects?:
                | T
                | {
                    title?: T;
                    description?: T;
                    category?: T;
                    image?: T;
                    size?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'featured-clients'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              ctaButtonText?: T;
              clients?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    row?: T;
                    order?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'why-brands-choose'?:
          | T
          | {
              sections?:
                | T
                | {
                    sectionLabel?: T;
                    mainHeading?: T;
                    description?: T;
                    featuresTitle?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    approachSteps?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'studio-section'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              description?: T;
              studioImages?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              perfectFor?:
                | T
                | {
                    item?: T;
                    id?: T;
                  };
              detailsSection?:
                | T
                | {
                    title?: T;
                    description?: T;
                    locationTitle?: T;
                    locationAddress?: T;
                    bookButtonText?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'page-hero'?:
          | T
          | {
              mainTitle?: T;
              description?: T;
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'service-cards'?:
          | T
          | {
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    color?: T;
                    servicesTitle?: T;
                    services?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    idealForLabel?: T;
                    idealForTags?:
                      | T
                      | {
                          tag?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        industries?:
          | T
          | {
              mainTitle?: T;
              industries?:
                | T
                | {
                    name?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'highlight-card'?:
          | T
          | {
              title?: T;
              description?: T;
              bulletPoints?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'cta-section'?:
          | T
          | {
              sectionLabel?: T;
              mainTitle?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  navigation?:
    | {
        label: string;
        /**
         * e.g., #services, #about, #studio
         */
        url: string;
        hasDropdown?: boolean | null;
        id?: string | null;
      }[]
    | null;
  ctaButton: {
    text: string;
    url: string;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  contactSection: {
    title: string;
    subtitle: string;
    formTitle: string;
  };
  companyInfo: {
    brandName: string;
    advertising: string;
    tagline: string;
    phone: string;
    email: string;
    location: string;
  };
  socialLinks?:
    | {
        platform: 'linkedin' | 'facebook' | 'instagram' | 'twitter';
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteTitle: string;
  siteDescription: string;
  ogImage?: (string | null) | Media;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        hasDropdown?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  contactSection?:
    | T
    | {
        title?: T;
        subtitle?: T;
        formTitle?: T;
      };
  companyInfo?:
    | T
    | {
        brandName?: T;
        advertising?: T;
        tagline?: T;
        phone?: T;
        email?: T;
        location?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteDescription?: T;
  ogImage?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}